run:
  timeout: 5m
  tests: true
  go: '1.26'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell

linters-settings:
  govet:
    disable:
      - shadow
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value of `.*\\.Close` is not checked"


