apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: platform
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: discord-subscriptions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: platform
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: discord-subscriptions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: platform
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: discord-subscriptions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
